services:
  # Servizio per lo SVILUPPO (Hot-Reload attivo)
  next-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps # Si ferma all'installazione delle dipendenze
    container_name: nextjs-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # Necessario se usi Windows/WSL2 per l'hot-reload
    command: npm run dev

  # Servizio per la PRODUZIONE (Immagine ottimizzata)
  next-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-prod
    ports:
      - "3001:3000" # Mappato sulla 3001 per non andare in conflitto con dev
    environment:
      - NODE_ENV=production
      # Inserisci qui le tue variabili SMTP che abbiamo configurato prima
      - SMTP_HOST=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_USER=noreply@gamarengineering.com
      - SMTP_PASS=jrnkyprcdwwtbldm